#!/bin/bash

usage () {
	echo "Usage: $0 rnaseq.conf rnaseq.tsv control_tag case_tag"
	echo " e.g.: $0 demo/rnaseq.conf demo/rnaseq.tsv wt mu"
	exit 1
}

if [ $# != 4 ] ; then
	usage
fi

if [ $1 == "-h" ] ; then
	usage
fi

target_file=$1
rnaseq_file=$2
control_tag=$3
case_tag=$4

if [ ! -f $target_file ]; then
	echo "Configuration file ($target_file) does not exist."
	usage
fi

if [ ! -f $rnaseq_file ]; then
	echo "RNAseq table file ($rnaseq_file) does not exist."
	usage
fi


out_dir="$PWD/$3_$4.rnadiff.outdir"
mkdir -p $out_dir

app=`which $0`
if [[ -L $app ]]; then
	app=`readlink -f $app`
fi
lib_dir=`dirname $app`

nohup Rscript $lib_dir/rnaseq.R $target_file $rnaseq_file $control_tag $case_tag $out_dir 1>$PWD/$3_$4.rnadiff_log.txt 2>&1 &
echo "Job submitted, outputs will be in $out_dir"
